analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: true
  exclude: 
    - lib/src/model/*.g.dart
  errors:
    deprecated_member_use_from_same_package: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unnecessary_import: ignore